const DASHBOARD_PATH = "/dashboard";

export enum NAVIGATION_PATHS {
  LOGIN = "/login",
  LANDING_PAGE = "/",
  DASHBOARD_HOME = `${DASHBOARD_PATH}/home`,
  DASHBOARD_AUDIT = `${DASHBOARD_PATH}/audit`,
  DASHBOARD_COURSES = `${DASHBOARD_PATH}/courses`,
  DASHBOARD_SCHEDULE = `${DASHBOARD_PATH}/schedule`,
  DASHBOARD_PROGRAMS = `${DASHBOARD_PATH}/programs`,
  NOT_YET_IMPLEMENTED = `${DASHBOARD_PATH}/*`, // TODO: Deprecate
}
